### ISSUE TITLE
Prepare the JSON Schema for capturing the test results

### ISSUE THREAD

**Issue by skounis** [skounis/eu-dcc-validation#2]
Work in progress
- https://github.com/skounis/eu-dcc-validation/blob/main/results.schema.json

The schema is generated by the provide sample using the [jsonschema.net](https://www.jsonschema.net/home) online tool.

**Comment by skounis** [comment]
@ryanbnl Before we close this, please review the following and check if we missed something?

* https://github.com/skounis/eu-dcc-validation/blob/main/results.schema.json
* https://github.com/skounis/eu-dcc-validation/blob/main/src/interfaces/model.interface.ts

Check also the generated JSON using the latest deployment
* https://eu-dcc-validation.web.app

**Comment by dslmeinte** [comment]
Observations:

- `ITestResultMetadata` has `completedOn` field while schema has `dateCompleted` field.
- Corresponding `dateCompleted` field doesn't have a format in the schema.
- Corresponding `platform` field has an enum type in TS, but not in the schema.
- `result` field (corresponding to `ITestResultEntry`) has an enum type in TS, but not in the schema.

**Comment by skounis** [comment]
@dslmeinte A PR related to your observation prepared. Could you please take a look?

- https://github.com/skounis/eu-dcc-validation/pull/38

**Comment by dslmeinte** [comment]
@skounis Done: approved. Just to confirm: the schema is primarily intended for _serialisation_, i.e.: describe what JSON will be produced? For deserialisation, I'd expect an additional layer of validation of incoming results JSON, because TypeScript allows you to cast `any` but will not actually do that type check at runtime.

**Comment by skounis** [comment]
@dslmeinte You are completely correct. Validation steps are still in the plan. I will create the related tickets in a while.

**Comment by skounis** [comment]
The last task is moved into its own ticked.
