### ISSUE TITLE
Upload screen

### ISSUE THREAD

**Issue by ryanbnl** [skounis/eu-dcc-validation#25]
Provide a screen where users can upload completed test results + submit them to the backend over the API, together with their authentication token.

**Comment by ryanbnl** [comment]
@skounis this will save a lot of work for Herbert and team, and ensure that all results come in via the portal.

**Comment by ryanbnl** [comment]
Or via automations which directly call the portal to submit, if MS so wish.

**Comment by skounis** [comment]
I'm closing this for time being since we do not have an API to call and we have an alternative in place: 
1. Download the `results.json`
2. Visit the portal (the link is provided) 
3. Upload and submit the `result.json`
